### PR TITLE
102 - Desktop access rights modified to comply with paper

### LINKED ISSUE #96: Check if there is an easy solution for checking desktop rights in C#
Or at least easier than currently done in `CageConfigurator.cs` - `StartedInCage()`. Maybe ask the service?

### PR DESCRIPTION
**Pull request by bencikpeter**
Access rights are now identical to those described in paper  (table 3) 

@DonatJR could you have a look at `StartedInCage()`  function in `CageChooser`? It will not work with new access rights and `C#` is not my friend... so I guess I need your help 😅 And maybe we could fix #96 at the same time (since this might not be the last rewrite, if rights ever change)

### CODE REVIEW

**Comment by DonatJR** [comment]
Alright, some points to discuss / think about:
* in order to being able to test the new `StartedInCage` method I had to think about how to solve #104, turns out displaying the UAC control is not the issue. The `CreateProcess...` family does not even try to display an elevation prompt but instead fails with `ERROR_ELEVATION_REQUIRED`.
  * Solution 1: Use `ShellExecute(Ex)` as it handles automatic elevation but I think cannot use a token to start a process
  * Solution 2: Check for this error and display our own elevation prompt, __this is currently rudimentarily implemented (thoughts?)__
* the access rights check itself works, but sometimes getting the sid in `{EXPLICIT_ACCESS-struct}.Trustee.ptstrName` fails (nullptr, [first occurence](https://github.com/SharkCagey/HTWG_shark_cage/pull/105/files#diff-e21d86ba5e172bf112c4a81c17a68449R265), [second occurence](https://github.com/SharkCagey/HTWG_shark_cage/pull/105/files#diff-e21d86ba5e172bf112c4a81c17a68449R303)). This seems to happen fairly randomly and I have currently no idea why this is happening (__maybe one of you has an idea__)
  * first I thought it might have something to do with the system process used to create our token as this process could be different each time, but I verified the same process was used with the problem happening and with it working
  * I also checked the `Trustee` struct on the C++ side after creating the new desktop with them, and here all values seem to be okay all the time

**Comment by SailReal** [comment]
If the `{EXPLICIT_ACCESS-struct}.Trustee.ptstrName` isn't null the current solution works like a charm 😍.
But as you discussed @DonatJR, randomly it is null but in my opinion, it is the right way to go. Will now have a look into the code in more detail, maybe I'll find out what's causing it.

Later we should enhance the dialog with more content that the user knows, it is more or less the same dialog like the UAC prompt with the same impact.

**Comment by SailReal** [comment]
Hmm, thought maybe one of [these](https://github.com/SharkCagey/HTWG_shark_cage/pull/105/commits/38d795271d36a0d7871845eb1fb2511b182e3f70) functions already fails, unfortunately not 🤨

**Comment by DonatJR** [comment]
Found the problem and will push a fix later today

**Comment by DonatJR** [comment]
Alright, this should fix the previous issue. The problem was that the `ACL` parameter retrieved by `GetSecurityInfo` apparently shares some data with the `security_descriptor` (last param of `GetSecurityInfo`). When freeing the `explicit_access` (was previously done right after the call to `GetSecurityInfo`) param the `ACL` param got corrupted / invalid.

Should have read the documentation more carefully:
> If the ppsidOwner, ppsidGroup, ppDacl, and ppSacl parameters are non-NULL, and the SecurityInfo parameter specifies that they be retrieved from the object, those parameters will point to the corresponding parameters __in the security descriptor__ returned in ppSecurityDescriptor.

🙈

**Comment by SailReal** [comment]
I have started the configurator a hundred times, with success and the and the explanation sounds reasonable. Thanks for the awesome fix 😍!!!

Will now look over the code again...

**Comment by SailReal** [comment]
@DonatJR should I put the release-mode check back in?

**Comment by DonatJR** [comment]
@bencikpeter the PR should now be ready to merge, I removed the `WIP` from the title. feel free to proceed ;)

**Pull request merged**
