### PR TITLE
fixes issues found by static analysis tools

### PR DESCRIPTION
**Pull request by DonatJR**
@bencikpeter There were some issues found in the `tokenLib` as well, here are all issues which I fixed in this PR:
tokenlib1
tokenlib2
tokenlib4a
tokenlib4b

There were also two issues __I did not yet fix__ (as I wasn't sure how to proceed):
tokenlib3 not fixed
tokenlib5 not fixed

As you can see the handles returned from `OpenProcess` are not closed if `hasSeCreateTokenPrivilege` or `processIsLocalSystem` throw an exception. I was not sure if you did not catch those on purpose. Any suggestions on the easiest way to deal with these issues? Do you want to do it yourself? (Maybe they are not even relevant anymore after #91?)

### CODE REVIEW

**Comment by bencikpeter** [comment]
@DonatJR  I´ll have a look at those issues and push directly into this PR if I may 😉

**Comment by DonatJR** [comment]
@bencikpeter Sure, go ahead

**Comment by bencikpeter** [comment]
@DonatJR could you please send me a full report? (I am not a HTWG student anymore, so no VPN 😞). I don´t quite understand what exactly the error is trying to say... I don´t throw any exeptions manually with `hasPrilivege` functions and WinAPI is C-oriented and does not throw as well.. that leads me to believe that only exceptions that can occur are runtime (like allocation error) but in that case, resoruce leaks should be reported here as well, since if constructor throws, destructor is not called and memory leak happens... but Coverity ignores it so it might mean something else? 🤔 

```cpp

tokenTemplate::tokenTemplate(HANDLE &userToken) {

	//load internal NtCreateToken function
	HMODULE hModule = LoadLibrary(L"ntdll.dll");
	NtCreateToken = (NT_CREATE_TOKEN)GetProcAddress(hModule, "NtCreateToken");

	//parse token
	DWORD bufferSize = 0;
	GetTokenInformation(userToken, TokenType, NULL, 0, &bufferSize);
	SetLastError(0);
	GetTokenInformation(userToken, TokenType, (LPVOID)&tokenType, bufferSize, &bufferSize);
	if (GetLastError() != 0)
	{
		throw TokenParsingException();
	}

	bufferSize = 0;
	GetTokenInformation(userToken, TokenUser, NULL, 0, &bufferSize);
	SetLastError(0);
	tokenUser = (PTOKEN_USER) new BYTE[bufferSize];
	GetTokenInformation(userToken, TokenUser, (LPVOID)tokenUser, bufferSize, &bufferSize);
	if (GetLastError() != 0)
	{
		throw TokenParsingException();
	}
```

**Comment by DonatJR** [comment]
@bencikpeter Unfortunately, I don't know how to get a pdf report from the website based static analysis tool these errors are from, sorry. :/

The exception probably stems from a call to `std::cout` with an integer-value. Your solution to free'ing the handle (and stopping the resource leak) looks good to me, I would have handled it the same way.

**Pull request merged**
